name: Run tests

on:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: aviate-labs/setup-dfx@v0.2.3
        with:
          vessel-version: 0.6.3
          dfx-version: 0.14.1

      - name: npm install
        run: npm install

      - name: test
        run: |
            npm start
            npm test